### ISSUE TITLE
CloudKit already has a convenience API in CKDatabase

### ISSUE THREAD

**Issue by malhal** [CloudKitSpace/CKRecordContext#1]
CloudKit already has a convenience API, e.g. in your demo app you could have just done CKDatabase saveRecord and saved yourself a couple of lines of code. I used to like wrapping APIs too but sometimes its good to take a step back and look at the big picture, e.g. in your class you've hidden away the record modification operation, which has some important properties on it, to open them up again you would need to provide an API into the inner workings of the record context. So essentially you are wrapping it up then unwrapping it again. I've slipped up on that a few times myself so now I've tried to not wrap anything, however I still make categories to add some extra functionality to existing classes. So for example you could add a category to CKDatabase to saveRecords that would be quite useful.

**Comment by nofelmahmood** [comment]
Thank you for the suggestions. I completely agree with you on this. But I think you misunderstood the whole point of this library. Firstly it just doesn't allows you to save records. It allows you to modify, save and delete instances of CKRecord. The changes continue to happen locally and they are not reflected on the CloudKit servers until and unless you call save on an instance of it. It only wraps this functionality for now.

It allows you to commit changes to the CloudKit Servers in a transaction like you would do to with any local database for efficiency. Calling saveRecord every time would require multiple network requests. This requires one which happens when you call save on an instance of it.

Secondly on hiding away the record modification operation I think I didn't had the intention of hiding it but I actually used it to provide this and only this particular functionality. Anyone who wants more out of it can use it directly. :)

Personally I think that this library may be more adaptable for those you have some CoreData background because they would I hope like it. Because they have been enjoying this for years through the use of [NSManagedObjectContext](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/CoreDataFramework/Classes/NSManagedObjectContext_Class/#//apple_ref/occ/instm/NSManagedObjectContext/).

Lastly you may have a look at [this](https://medium.com/p/cloudkit-in-context-1efd6ec23ed1).

Happy Coding :)

**Comment by malhal** [comment]
Please take a look at categories, what you said in paragraph 3 is exactly what those are for.

It's interesting you are trying to make CloudKit more like traditional CoreData, there are a couple of hints that Apple are moving CoreData towards a more of an async API in CloudKit like they did with NSURLSession since they added NSBatchUpdateRequest/NSAsynchronousFetchRequest which in theory take all the pain out of threading. A way to save single records to core data async but still have them in the context (unlike batch update) would be a pretty cool feature.
